# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingblock',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
